# Generated by Django 4.2.5 on 2023-11-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default=0),
        ),
    ]
