# Generated by Django 4.2.5 on 2023-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0002_ingredient_kcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ingredient', max_length=50)),
                ('protein', models.FloatField(default=0, verbose_name='protein/100g_ml')),
                ('carbs', models.FloatField(default=0, verbose_name='carbs/100g_ml')),
                ('fat', models.FloatField(default=0, verbose_name='fat/100g_ml')),
                ('kcal', models.FloatField(default=0, verbose_name='kcal/100g_ml')),
                ('cup_factor', models.FloatField(default=0, verbose_name='Avg cup weight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ingredient', max_length=50)),
                ('protein', models.FloatField(default=0, verbose_name='protein/100g_ml')),
                ('carbs', models.FloatField(default=0, verbose_name='carbs/100g_ml')),
                ('fat', models.FloatField(default=0, verbose_name='fat/100g_ml')),
                ('kcal', models.FloatField(default=0, verbose_name='kcal/100g_ml')),
                ('piece_factor', models.IntegerField(default=0, verbose_name='Avg piece weight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
