# Generated by Django 4.2.5 on 2023-11-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0007_ingredient_recipe_recipeingredient_delete_drink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Calculator.ingredient'),
            preserve_default=False,
        ),
    ]
