# Generated by Django 4.2.5 on 2023-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0008_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='g', max_length=4),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
