# Generated by Django 4.2.5 on 2023-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0009_recipeingredient_unit_alter_recipeingredient_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
