# Generated by Django 4.2.5 on 2023-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0010_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='Calculator.recipeingredient'),
        ),
    ]
