# Generated by Django 4.2.5 on 2023-12-04 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calculator', '0011_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('recipeingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Calculator.recipeingredient')),
            ],
            bases=('Calculator.recipeingredient',),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_as_ingredient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calculator.ingredient'),
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
