# Generated by Django 4.2.5 on 2024-02-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0012_meal_recipe_recipe_as_ingredient_calendarday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meal',
            name='calendar_day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='Calculator.calendarday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('d', 'Dessert'), ('S', 'Snack'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calculator.recipe'),
        ),
    ]
