# Generated by Django 4.2.5 on 2024-02-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0013_remove_recipe_ingredients_meal_calendar_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calendar_day',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipeingredient_ptr',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Calculator.recipe'),
        ),
        migrations.DeleteModel(
            name='CalendarDay',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
